# ============================================================
# ARENA CONFIG
# ============================================================

arena_size_mm: 500

apriltag: 
  
  tag_size_mm: 80 
  
  min_margin: 25

apriltags:

  # corners
  0: [-160,  160]
  2: [-160, -160]

  4: [ 160, -160]
  6: [ 160,  160]

  # edge centers
  1: [-160, 0]
  5: [ 160, 0]

  3: [0, -160]
  7: [0,  160]

# ============================================================
# CAMERA CONFIG
# ============================================================

camera: 
  
  width: 1920 
  
  height: 1080 
  
  fps: 30

# ============================================================
# TRANSFORM CONFIG
# ============================================================

bird_view: 

  scale: 2.0 

  padding: 200 

  crop_size: 400 

  homography_alpha: 0.2

# ============================================================
# DETECTION CONFIG
# ============================================================

detection:

  min_area: 2500 
  
  min_circularity: 0.25

  colors:

    green:

      lower_hsv: [35, 60, 40]
      upper_hsv: [90, 255, 255]

    red_1:

      lower_hsv: [0, 80, 50]
      upper_hsv: [10, 255, 255]

    red_2:

      lower_hsv: [170, 80, 50]
      upper_hsv: [180, 255, 255]

    blue:

      lower_hsv: [90, 80, 40]
      upper_hsv: [130, 255, 255]

    yellow:

      lower_hsv: [20, 80, 80]
      upper_hsv: [35, 255, 255]

# ============================================================
# QUADRATIC CALIBRATION CONSTANTS
# ============================================================

quadratic_calibration:

  x:

    c0: 0.5444
    c1: 0.9551
    c2: 0.000777
    c3: 0.0000185
    c4: 0.0000265
    c5: 0.0000281

  y:

    c0: 18.0632
    c1: -0.000410
    c2: 0.9436
    c3: 0.0000131
    c4: -0.0000105
    c5: 0.0000367

# ============================================================
# CAMERA ↔ ROBOT SYNC
# ============================================================

robot_sync:

  tx_mm: 0.0
  ty_mm: 0.0

  rotation_deg: 0.0

# ============================================================
# ROBOT WORKSPACE
# ============================================================

workspace:

  xmin: -100
  xmax:  100

  ymin: -100
  ymax:  100

  safe_radius_mm: 120

# ============================================================
# PICK CONFIG
# ============================================================

robot:

  pick_z_mm: -310.0